version: '3.8'

services:
  app:
    build: .
    container_name: job4you-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/job4you_db
      - SPRING_DATASOURCE_USERNAME=job4you_user
      - SPRING_DATASOURCE_PASSWORD=job4you_password
      - APP_JWTSECRET=your_jwt_secret_key
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_USERNAME=your_email@gmail.com
      - SPRING_MAIL_PASSWORD=your_app_password
    depends_on:
      - db
    networks:
      - job4you-network
    volumes:
      - app-logs:/app/logs

  db:
    image: postgres:13
    container_name: job4you-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=job4you_db
      - POSTGRES_USER=job4you_user
      - POSTGRES_PASSWORD=job4you_password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - job4you-network

networks:
  job4you-network:
    driver: bridge

volumes:
  db-data:
  app-logs:

