// Code JS pour le nœud "Préparer données entretien" de l'Agent 3 n8n
// Utilise var + concaténation (pas de template literals ni apostrophes dans HTML)
module.exports = [
  "var data = $input.first().json.body || $input.first().json;",
  "var candidatEmail  = data.candidatEmail || '';",
  "var candidatNom    = data.candidatNom   || '';",
  "var candidatPrenom = data.candidatPrenom || '';",
  "var rhEmail        = data.rhEmail       || 'bargaouihaythem1@gmail.com';",
  "var offreTitre     = data.offreTitre    || 'le poste';",
  "var type           = data.type          || 'HR';",
  "var lieu           = data.lieu          || 'A definir';",
  "var dateEntretien  = data.dateEntretien ? new Date(data.dateEntretien).toLocaleString('fr-FR') : 'A confirmer';",
  "var meetLink = 'https://meet.google.com/' + Math.random().toString(36).substr(2, 10);",
  "var meetBtn = '<a href=\"' + meetLink + '\" style=\"display:inline-block;background:#4285f4;color:white;padding:10px 20px;border-radius:5px;text-decoration:none;font-weight:bold\">Rejoindre Google Meet</a>';",
  "var css = '<style>body{font-family:Arial,sans-serif;line-height:1.6;color:#333;max-width:600px;margin:0 auto;padding:20px}' +",
  "  '.hdr{background:#17a2b8;color:white;padding:20px;text-align:center;border-radius:5px 5px 0 0}' +",
  "  '.cnt{background:#f8f9fa;padding:30px;border-radius:0 0 5px 5px}' +",
  "  '.box{background:white;padding:20px;margin:20px 0;border-left:4px solid #17a2b8;border-radius:5px}' +",
  "  '.rw{margin:10px 0;padding:5px 0;border-bottom:1px solid #e9ecef}' +",
  "  '.lbl{font-weight:bold;display:inline-block;min-width:130px}' +",
  "  '.warn{background:#fff3cd;border:1px solid #ffeaa7;padding:15px;border-radius:5px;margin:15px 0}' +",
  "  '.ftr{text-align:center;margin-top:30px;padding-top:20px;border-top:1px solid #dee2e6;color:#6c757d;font-size:14px}' +",
  "  '</style>';",
  "var head = '<!DOCTYPE html><html><head><meta charset=\"UTF-8\">' + css + '</head>';",
  "var emailCandidatHtml = head + '<body>';",
  "emailCandidatHtml += '<div class=\"hdr\"><h1>Invitation a un entretien</h1></div>';",
  "emailCandidatHtml += '<div class=\"cnt\">';",
  "emailCandidatHtml += '<p>Bonjour <strong>' + candidatPrenom + ' ' + candidatNom + '</strong>,</p>';",
  "emailCandidatHtml += '<p>Nous avons le plaisir de vous inviter a un entretien pour le poste :</p>';",
  "emailCandidatHtml += '<h3 style=\"color:#17a2b8;text-align:center\">' + offreTitre + '</h3>';",
  "emailCandidatHtml += '<div class=\"box\"><h4>Details :</h4>';",
  "emailCandidatHtml += '<div class=\"rw\"><span class=\"lbl\">Type :</span>' + type + '</div>';",
  "emailCandidatHtml += '<div class=\"rw\"><span class=\"lbl\">Date et heure :</span>' + dateEntretien + '</div>';",
  "emailCandidatHtml += '<div class=\"rw\"><span class=\"lbl\">Lieu :</span>' + lieu + '</div>';",
  "emailCandidatHtml += '<div class=\"rw\"><span class=\"lbl\">Lien Meet :</span>' + meetBtn + '</div>';",
  "emailCandidatHtml += '</div>';",
  "emailCandidatHtml += '<div class=\"warn\"><ul>';",
  "emailCandidatHtml += '<li>Merci de confirmer votre presence</li>';",
  "emailCandidatHtml += '<li>Veuillez arriver 10 min avant</li>';",
  "emailCandidatHtml += '<li>En cas d empechement, prevenez-nous</li>';",
  "emailCandidatHtml += '</ul></div>';",
  "emailCandidatHtml += '<p>Cordialement,<br>L equipe de recrutement JOB4YOU</p>';",
  "emailCandidatHtml += '</div><div class=\"ftr\"><p>Email automatique - JOB4YOU 2026</p></div></body></html>';",
  "var emailRhHtml = head + '<body>';",
  "emailRhHtml += '<div class=\"hdr\"><h1>Entretien planifie avec succes</h1></div>';",
  "emailRhHtml += '<div class=\"cnt\">';",
  "emailRhHtml += '<p>L entretien suivant a ete planifie et le candidat a ete notifie :</p>';",
  "emailRhHtml += '<div class=\"box\">';",
  "emailRhHtml += '<p><strong>Candidat :</strong> ' + candidatPrenom + ' ' + candidatNom + '</p>';",
  "emailRhHtml += '<p><strong>Email :</strong> ' + candidatEmail + '</p>';",
  "emailRhHtml += '<p><strong>Poste :</strong> ' + offreTitre + '</p>';",
  "emailRhHtml += '<p><strong>Type :</strong> ' + type + '</p>';",
  "emailRhHtml += '<p><strong>Date et heure :</strong> ' + dateEntretien + '</p>';",
  "emailRhHtml += '<p><strong>Lieu :</strong> ' + lieu + '</p>';",
  "emailRhHtml += '<p><strong>Lien Meet :</strong> ' + meetBtn + '</p>';",
  "emailRhHtml += '</div>';",
  "emailRhHtml += '<p>Cordialement,<br>La plateforme JOB4YOU</p>';",
  "emailRhHtml += '</div><div class=\"ftr\"><p>Email automatique - JOB4YOU 2026</p></div></body></html>';",
  "return [{ json: { candidatEmail, candidatNom, candidatPrenom, rhEmail, offreTitre, type, lieu, dateEntretien, meetLink, emailCandidatHtml, emailRhHtml } }];"
].join('\n');
